# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import keyboard_pb2 as keyboard__pb2


class KeyboardStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetKeyboard = channel.unary_stream(
                '/keyboardsender.Keyboard/GetKeyboard',
                request_serializer=keyboard__pb2.KeyStroke.SerializeToString,
                response_deserializer=keyboard__pb2.KeyStroke.FromString,
                )


class KeyboardServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetKeyboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyboardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetKeyboard': grpc.unary_stream_rpc_method_handler(
                    servicer.GetKeyboard,
                    request_deserializer=keyboard__pb2.KeyStroke.FromString,
                    response_serializer=keyboard__pb2.KeyStroke.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'keyboardsender.Keyboard', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Keyboard(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetKeyboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/keyboardsender.Keyboard/GetKeyboard',
            keyboard__pb2.KeyStroke.SerializeToString,
            keyboard__pb2.KeyStroke.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
